### ISSUE TITLE
Scrollbar Not Working at Top Right Corner of Browser Window

### ISSUE THREAD

**Issue by netlander** [tomastrajan/angular-ngrx-material-starter#221]
There is an overlap problem with the toolbar and the scrollbar where it's not possible to click and drag the scrollbar at the top right of the browser window as depicted in the image below.

![scrollbar-problem](https://user-images.githubusercontent.com/4721044/40788237-82865d90-64e7-11e8-91cb-bc5125e56391.png)

**Comment by tomastrajan** [comment]
Thank you for reporting the issue! The whole main layout was reworked and it should work now. It will be live on the demo page once the release `v6.3.0` was created and deployed (check current version in the bottom right corner of the page).

**Comment by netlander** [comment]
Actually I have come to the same solution namely resorting to an ugly CSS hack to move the scrollbar below the toolbar. Will take a look at your approach at some point.

**Comment by pnguyen535** [comment]
Hi,

I still have the issue with the latest code. I think the stickyHeader creates issue.

Thanks

<div class="toolbar" [style.position]="(stickyHeader$ | async) ? 'fixed' : 'inherit'" [class.mat-elevation-z4]="(stickyHeader$ | async)">

**Comment by bigozzi-inspect** [comment]
Hi, the problem is still here :sob: 

@netlander, can you share your ugly (but working) CSS hack? :pray: 

Thanks you!

**Comment by bigozzi-inspect** [comment]
**Append to app.component.scss:**

```
// Workaround for https://github.com/tomastrajan/angular-ngrx-material-starter/issues/221
@media (min-width: map-get($grid-breakpoints, md)) {
  mat-sidenav-container,
  mat-sidenav-content {
    overflow: unset;
  }
}
```

**Replace in app.componenet.scss:**

```
<div class="wrapper">
  [...]
</div>
```
to
```
<mat-sidenav-content>
  <div class="wrapper">
    [...]
  </div>
</mat-sidenav-content>
```

**Comment by netlander** [comment]
> Hi, the problem is still here 😭
> 
> @netlander, can you share your ugly (but working) CSS hack? 🙏
> 
> Thanks you!

@bigozzi-inspect It seems like an eternity since I worked on this, I wouldn't know where to begin looking at that old hack I used, sorry I can't be of much help (front-end development isn't my primary dev environment).
